controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - Leher Putar
      - Kepala Putar 
      - Paha Kanan Putar
      - Paha Kiri Putar
      - Lengan Kiri
      - Bahu Tangan Kiri
      - Tangan Kiri
      - Lengan Kanan
      - Bahu Tangan Kanan
      - Tangan Kanan
      - Paha Atas Kanan
      - Paha Bawah Kanan
      - Paha Atas Kiri
      - Paha Bawah Kiri
      - Lutut Kanan
      - Lutut Kiri
      - Kaki Kanan Atas
      - Kaki Kiri Atas
      - Kaki Kiri Bawah
      - Kaki Kanan Bawah
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      
    allow_partial_joints_goal: true